version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: tubee_db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-tubee}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    ports:
      - "3306:3306"

volumes:
  db-data:
